AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # A bucket that hosts the website.
  S3BucketWebsite:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: gymlog.indianakernick.com
      Tags:
        - Key: project:gym-log
      WebsiteConfiguration:
        IndexDocument: index.html

  # The main database for all user data.
  DynamoDbTableUser:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ModifiedVersion
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI-ModifiedVersion
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: ModifiedVersion
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      TableClass: STANDARD
      TableName: gym-log.User
      Tags:
        - Key: project:gym-log

  # A Cognito user pool using a fairly basic email and password configuration.
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AliasAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Mutable: false
          Name: email
          Required: true
      UserPoolName: gym-log
      UserPoolTags:
        - Key: project:gym-log

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Retain
    Properties:
      AccessTokenValidity: 60
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AuthSessionValidity: 3 # minutes
      ClientName: gym-log
      EnableTokenRevocation: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      GenerateSecret: false
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  # The execution role for the proxy Lambda function. This allows the Lambda to
  # write CloudWatch logs and access the database.
  IamRoleLambdaProxyExecution:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                # We can't !Sub the Lambda name because that creates a circular
                # dependency.
                Resource: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/gym-log.proxy:*
          PolicyName: gym-log.lambda.log
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                Resource:
                  - !Sub
                    - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}
                    - Table: !Ref DynamoDbTableUser
                  - !Sub
                    - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}/index/*
                    - Table: !Ref DynamoDbTableUser
          PolicyName: gym-log.lambda.dynamodb
      MaxSessionDuration: 3600 # seconds
      RoleName: gym-log.lambda
      Tags:
        - Key: project:gym-log

  # The proxy Lambda function processes all API requests from API Gateway.
  LambdaProxy:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      Architectures:
        - arm64
      Code:
        # wondering if I can run CloudFormation and then run
        # update-function-code to avoid creating another S3 bucket
        ZipFile: ""
      Environment:
        Variables:
          RUST_BACKTRACE: "1"
      FunctionName: gym-log.proxy
      Handler: bootstrap
      MemorySize: 128 # MB
      PackageType: Zip
      Role: !GetAtt IamRoleLambdaProxyExecution.Arn
      Runtime: provided.al2
      Tags:
        - Key: project:gym-log
      Timeout: 3

  Api:
    Type: AWS::ApiGatewayV2::Api
    DeletionPolicy: Retain
    Properties:
      FailOnWarnings: true
      Name: gym-log
      ProtocolType: HTTP
      Tags:
        - Key: project:gym-log

  ApiStageDefault:
    Type: AWS::ApiGatewayV2::Stage
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AutoDeploy: true
      DeploymentId: !Ref ApiDeployment
      StageName: $default
      Tags:
        - Key: project:gym-log

  ApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api

  # An authorizer that will parse the Authorization HTTP header as a JWT. It
  # will use the issuer URI to get the public key and verify the signature. It
  # will also check the issuer, audience and expiry claims.
  ApiAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerType: JWT
      IdentitySource: $request.header.Authorization
      JwtConfiguration:
        Audience:
          - !Ref CognitoUserPoolClient
        Issuer: !GetAtt CognitoUserPool.ProviderURL
      Name: gym-log

  # An integration that forms the bridge between an API Gateway route and the
  # proxy Lambda.
  ApiIntegrationProxy:
    Type: AWS::ApiGatewayV2::Integration
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaProxy.Arn
      # The documentation doesn't say that there's a Name property but I can set
      # a name in the console.
      Name: gym-log
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  # Below are the route definitions for the whole API. There are OPTIONS routes
  # that are handled by the proxy Lambda for CORS. API Gateway has a built-in
  # mechanism for dealing with CORS but it didn't seem to work.

  ApiRouteUserGet:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: GET /user
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserOptions:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserMeasurementDelete:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: DELETE /user/measurement/{measurementId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserMeasurementOptions:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user/measurement/{measurementId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserMeasurementPut:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: PUT /user/measurement/{measurementId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutDelete:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: DELETE /user/workout/{workoutId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutOptions:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user/workout/{workoutId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutPut:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: PUT /user/workout/{workoutId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutExerciseDelete:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: DELETE /user/workout/{workoutId}/exercise/{exerciseId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutExerciseOptions:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user/workout/{workoutId}/exercise/{exerciseId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutExercisePut:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: PUT /user/workout/{workoutId}/exercise/{exerciseId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutOrderOptions:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user/workout/{workoutId}/order
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

  ApiRouteUserWorkoutOrderPut:
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Retain
    Properties:
      ApiId: !Ref Api
      AuthorizerId: !Ref ApiAuthorizer
      RouteKey: PUT /user/workout/{workoutId}/order
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegrationProxy

Outputs:
  CognitoClientId:
    Value: !Ref CognitoUserPoolClient
  ApiBaseUrl:
    Value: !Sub
      - https://${Id}.execute-api.${AWS::Region}.amazonaws.com
      - Id: !Ref Api
