AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gymlog.indianakernick.com
      Tags:
        - Key: project:gym-log
      WebsiteConfiguration:
        IndexDocument: index.html

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ModifiedVersion
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI-ModifiedVersion
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: ModifiedVersion
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      TableClass: STANDARD
      TableName: gym-log.User
      Tags:
        - Key: project:gym-log

  LambdaProxy:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Environment:
        Variables:
          RUST_BACKTRACE: "1"
      FunctionName: gym-log
      Handler: bootstrap
      MemorySize: 128
      PackageType: Zip
      Tags:
        - Key: project:gym-log
      Timeout: 3

  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      FailOnWarnings: true
      Name: gym-log
      ProtocolType: HTTP
      Tags:
        - Key: project:gym-log

  ApiStageDefault:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref Api
      AutoDeploy: true
      StageName: $default
      Tags:
        - Key: project:gym-log

  ApiRouteUserOptions:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: OPTIONS /user

  ApiRouteUserGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      AuthorizationType: JWT
      RouteKey: GET /user

  ApiIntegrationProxy:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaProxy.Arn
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000
